### ISSUE TITLE
the bottom of the frequency seems unusable when Lo is 16MHZ (juste for maybe wiki information?)

### ISSUE THREAD

**Issue by F4HTB** [ik1xpv/ExtIO_sddc#114]
Hello,

Receiver: RX888
Software: HDSDR v2.80 installer with OmniRig V2 support. (March 19, 2020)
DLL: ExtIO_sddc_v1.1RC1.zip from https://github.com/ik1xpv/ExtIO_sddc/releases/download/v1.1/ExtIO_sddc_v1.1RC1.zip
OS: Windows 10 1909

If you are stubborn like me, you tend to set the "Lo" to Bandwidth / 2 and lock.

It might be nice to note somewhere that when you want to use the edges correctly like LF MF, you have to lower the LO even to see the frequencies <0hf and of course AGC on OFF.

73 F4HTB

**Comment by ik1xpv** [comment]
When I want to receive LW MW my procedure is;

1) I set the SR to 4Msps , the reason is that the band filter has not a sharp cutoff so 2Msps gives a useful bandwidth of about 1.5MHz to narrow for 0-2 MHz span,
2) tune LO display to 1 MHz and lock it 
The locking of LO is done moving the mouse on LO label left of display and clicking right button of mouse.
3) move the zoom control of HDSDR to see spectrum from 0 to 2MHz.

Thanks for the reports
Ciao
Oscar

**Comment by ik1xpv** [comment]
Maybe I have an explanation of what is happening to your tuning.
If I select the 16MHz bandwidth and I set the LO to 7MHz I get the full spectrum like this
![image](https://user-images.githubusercontent.com/9883800/102720525-2465bc80-42f5-11eb-99cc-c65bd838b62d.png)
while if I set the LO at 8MHz I get the following situation
![image](https://user-images.githubusercontent.com/9883800/102720569-7870a100-42f5-11eb-84aa-3238e540f640.png)
The tuning of my preferred 999 KHz station is still possible but the LW are filtered out by the bandpass filter cutoff.
I hope to be of some help.
Ciao
Oscar

**Comment by howard0su** [comment]
@ik1xpv  we may need to maintain a wiki page to host the common FAQ.

**Comment by ik1xpv** [comment]
Yes a wiki page is todo. I'll try. :-)

**Comment by ik1xpv** [comment]
A tentative page on
https://github.com/ik1xpv/ExtIO_sddc/wiki/ExtIO_sddc---HDSDR--FAQ
