### ISSUE TITLE
Two devices on the same system at the same time

### ISSUE THREAD

**Issue by ik1xpv** [ik1xpv/ExtIO_sddc#209]
I received a request from Joanne Dow.

Two RX888s on the same system at the same time?
Is there a way to change the serial number on one of them so that they can be unambiguously selected?

**Comment by fventuri** [comment]
Joanne, perhaps it's just me, but I don't see any image attached to your comment above.

Franco

**Comment by ik1xpv** [comment]
Hi,
I  made a try with  devcon.exe [https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/devcon](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/devcon)

I disconnected the two _Cypress FX3 USB BootLoader Devices_ and exchange the cables 
The numbers depends on the USB ports. They do not depends on Fx3 devices (is we use the internal rom boot loader !
test file : [devcon.txt](https://github.com/ik1xpv/ExtIO_sddc/files/7444820/devcon.txt)

I think that CyAPI.lib uses the same port order and it does not change if we uses the same USB ports connection (?)

Oscar

**Comment by ms-jdow** [comment]
Try again
![RX888 IDs](https://user-images.githubusercontent.com/10334717/139528443-f8ab8223-d5bc-4eef-889d-b699d7003f05.png)
:

{^_^}

**Comment by ik1xpv** [comment]
Thanks Joanne,

The Device Instance path or Device Instance ID   [https://docs.microsoft.com/en-us/windows-hardware/drivers/install/device-instance-ids](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/device-instance-idsl)  is persistent across system restarts.
The Instance ID [https://docs.microsoft.com/en-us/windows-hardware/drivers/install/instance-ids](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/instance-ids)  is a device identification string that distinguishes a device from other devices of the same type on a computer. An instance ID contains serial number information, **if supported by the underlying bus** (_NO in our today code_), or **some kind of location information** (_YES we are here_). 

I connected two SDRs to the PC. I run two instances of HDSDR.
I run devcon and I get
_...
c:\Program Files (x86)\Windows Kits\10\Tools\x64>devcon listclass USB
Listing 15 devices in setup class "USB" (Controller USB (Universal Serial Bus)).
...
USB\VID_04B4&PID_00F1\5&5E31287&1&6                         : Cypress FX3 USB StreamerExample Device
USB\VID_04B4&PID_00F1\5&5E31287&1&8                         : Cypress FX3 USB StreamerExample Device
..._
Then I close the HDSDR apps disconnect the SDRs exchange the cable/USB ports.  Run HDSDR again.
devcon now shows:
_c:\Program Files (x86)\Windows Kits\10\Tools\x64>devcon listclass USB
Listing 15 devices in setup class "USB" (Controller USB (Universal Serial Bus)).
...
USB\VID_04B4&PID_00F1\5&5E31287&1&6                         : Cypress FX3 USB StreamerExample Device
USB\VID_04B4&PID_00F1\5&5E31287&1&8                         : Cypress FX3 USB StreamerExample Device
..
c:\Program Files (x86)\Windows Kits\10\Tools\x64>_
The IDs depend only on the used port and do not identify the specific device connected (they are  the location information as we have no Serial Numbers on the devices).
This is the information used in CyAPI.lib to identify many devices of the same kind connected to the pc,
The pull #210 tries to use it to identify two path on the same pc

Ciao,
Oscar

**Comment by fventuri** [comment]
Oscar,
I finally found some time to look at page 47 of the FX3 tech manual 2019 (the document you referred to in the comment a few days ago), and the two registers that contain the unique FX3 id at memory locations 0xE0055010 and 0xE0055014 (see here: https://community.infineon.com/t5/USB-Superspeed-Peripherals/Unique-Id-Registers-in-CYUSB3014/m-p/201271) are **not** in the BootROM region (which begins at 0xF000000), but in the MMIO register space (from 0xE0000000 to 0xEFFFFFFF), which is described as follows:

> MMIO-The register space that holds all the configuration and status registers implemented by all the blocks on the FX3 
device. While a total memory region of 256 MB has been allocated for the registers, most of this memory is unused and 
unimplemented. Refer to the chapters on each of the FX3 hardware blocks for information on the registers corresponding 
to those blocks.

and therefore you should be able to read them and use them to create a unique serial number for each BBRF103, HF103, RX-888, etc

Looking at the code in this example (https://community.infineon.com/t5/USB-Superspeed-Peripherals/FX3-Unique-ID-is-same-for-more-than-one-device/m-p/115063/highlight/true#M10249), it should be as easy as adding these two lines to the SDDC firmware (at least to try to see what they print out):

```
                status = CyU3PReadDeviceRegisters((uvint32_t *)0xE0055010,2,ID);
                CyU3PDebugPrint(4,"\r\n Read device register %d,0x%x,0x%x\n",status,ID[1],ID[0]);
```

Ciao from Florida,
Franco

**Comment by ik1xpv** [comment]
Franco,
YES ! That's a very good news !  Thanks!  :-))
I like the message in your forum link:
**There will be a 64bits unique ID for each die of FX3**. You can read these bits from the address location 0xE0055010
In the next week I will dig in FX3 firmware adding serial number reading.
I will take some time since I have to refresh my memory on Arm :-) 
I like the fact that possibly it is not required to program any device in the field as the SN is just there ! ! !

Have you All a nice weekend,
Ciao
Oscar

**Comment by ms-jdow** [comment]
Ooooh - I like this Franco guy. {^_-} That sounds very very promising. Thank you sir!

{^_^}

**Comment by fventuri** [comment]
Oscar, Joanne, glad to be able to help! (and my apologies for the confusion about KUSC's birthday and yours)

Tonight, following Cypress forums suggestions here:  https://community.infineon.com/t5/USB-Superspeed-Peripherals/FX3-Device-Name/m-p/287956 , I made a few changes to the firmware file USBdescriptor.c so that it should return this unique FX3 id as the serial number (the modified file is attached below).

All I could check here is that the file with the changes compiles without errors (I unrolled the loop that assigns the 16 hex digits of the serial number; if you prefer, those lines can be changed to a couple of 'for' loops; in 'normal' C one would have used 'snprintf()', but I don't think it is an option here because it allocates heap memory).

Please take a look at the changes, and, if you feel like trying it, let me know how it goes.

Franco

[USBdescriptor.c.gz](https://github.com/ik1xpv/ExtIO_sddc/files/7447812/USBdescriptor.c.gz)

**Comment by ms-jdow** [comment]
Franco, your comment raises a question for Oscar. If you are using Visual Studio 19 why not use its make facility and compiler? It would save putting extraneous "stuff" on your machine? (That's one of the reasons I've not gone in and tinkered myself. I may still do so and make a proper project. DLLs and I are usually good friends.)

What is it about snprintf that this build environment does not like? _snprintf_s is almost a direct replacement. It just adds a destination size parameter.

{^_^}

**Comment by fventuri** [comment]
First of all, I am an old school Linux/vi/make kind-of guy, so no VS, Eclipse, IntellJ at my house :-)

This said, I used the instructions in the ExtIO_sddc README (https://github.com/ik1xpv/ExtIO_sddc#build-instructions-for-firmware) to build the firmware (which was just typing 'make', since I already have he ARM toolchain here), and I was able to compile it (I had to fix one very minor thing in 'rx999.c', but that is unrelated).

So I have the modified firmware here, but I don't own any of these SDRs; that's why I said earlier that I can only make sure it compiles.

As per the thing with 'sprintf()', yesterday I was reading this thread on the Cypress FX3 community forums (https://community.infineon.com/t5/USB-Superspeed-Peripherals/FX3-Fail-to-call-sprintf-function-for-float-on-C-project/m-p/272300), and it made me think that perhaps using 'sprintf()' to just convert 16 hexadecimal values to characters is overkill, and that's the reason of the approach I took in the modified USBdescriptor.c

Franco

**Comment by ik1xpv** [comment]
Welcome on board Joanne ! 
I like to play with DSP code.  The repository comes from to the  ideas and had work by Hayati Ayguen,  Howard Su , Franco Venturi  and me.  Howard built also the automate workflow  They tried to teach me how to use Github. I am fond of it and I thank them for their patience.
I suggest you to fork the repository to exercise and pull your requests.  The [readme](https://github.com/ik1xpv/ExtIO_sddc#readme) describes the environment setup and it's the starting point as Franco said.
I use VS2019 as compiler but I compile the Arm code in Linux environment.  I personally use GihHub desktop  or direct Github in the browser.

Franco, yes! we could also change the Product name to the specific hardware found
I'm testing it ..
<DEVICE>
	FriendlyName="Cypress FX3 USB StreamerExample Device"
	Manufacturer="sdr-prototypes.blogspot.com"  _// <- I think of "Open Source at GitHub\,,," ? ?_
	Product="BBRF103"                                           _//  or RX888, RX888mk2 , HF103 ...._
	SerialNumber="012345678901" 
....

Oscar

**Comment by fventuri** [comment]
Joane, welcome on board from me too!
I apologize if my earlier comment about Linux was harsh and snarky - I really appreciate working with Oscar and the others and all the things I learned from them, and you are most welcome to join us!

Oscar,
I like your ideas; I would also like to see if it is possible to get away from Cypress' own USB VID and PID, that we are probably not supposed to be using at this point. On that regard, I found this email from a bit ago:

> I also suggest that we take the opportunity of the new firmware to 'move out' from Cypress 'streamer example' PID/VID in the USB descriptor, since according to Cypress you are not supposed to use it (https://community.cypress.com/docs/DOC-12682).
> 
> I did some quick research and I found a few options:
> - request a free USB product id from Openmoko (see here: http://wiki.openmoko.org/wiki/USB_Product_IDs); they are free for open source projects
> - another similar option is pid.codes (https://pid.codes/)
> - purchase one from MCS (https://www.mcselec.com/index.php?page=shop.product_details&flypage=shop.flypage&product_id=92&option=com_phpshop&Itemid=1) - this would allow for commercial development too, but you may want to read the disclaimer in that page first, about USB-ORG stance on those PID/VIDs
> - finally one (with deep pockets!) could buy a whole USB PID from USB-ORG (it allows for 64k VIDs, similar to a class B Internet network), but I think those cost $6k or something like that

This was a year or so ago; it is possible that there are more and different options now.
Since this is an open source project, perhaps we should look at applying with Openmoko or pid.codes, since they are free.

Franco

**Comment by ik1xpv** [comment]
Franco,

The advantage of using  Cypress VID/PID is also in use of Cypress certified driver.
At development stage as we are now it seems to me a correct use with the limit Cypress states
_" If the Cypress VID is used for an end product, then many customers could use the same VID, which could cause a malfunction because an end product may bind to an incorrect driver "_
The fact that we have no eeprom forces us to use the VID/PID Cypress for the "Cypress FX3 BootLoader Device"  anyway before we could load a custom VID/PID image in ram,
It seems to me that the different VID/PID is the path to follow for someone that make a product with eeprom to house the firmware of  FX3 or a custom boot. Only in this way it will be free from collision with the "Cypress FX3 BootLoader Device",

At the moment I like to test your ideas and code. I plan to have some test result middle of next week as I will be offline tomorrow.

Oscar

**Comment by ik1xpv** [comment]
Update
I made a rapid test of your serial number code on two devices. All ok !
Here the Cypres USB  control center output
<DEVICE >
	FriendlyName="Cypress FX3 USB StreamerExample Device"
	Manufacturer="sdr-prototypes.blogspot.com"
	Product="RX888"
	SerialNumber="0008012400431D31"
---
<DEVICE>
	FriendlyName="Cypress FX3 USB StreamerExample Device"
	Manufacturer="sdr-prototypes.blogspot.com"
	Product="RX888mk2"
	SerialNumber="0009023200531716"

I plan commit on Tuesday or Wednesday.
Ciao Oscar

**Comment by ik1xpv** [comment]
Update
I made a rapid test of your serial number code on two devices. All ok !
Here the Cypres USB control center output
Device 1
FriendlyName="Cypress FX3 USB StreamerExample Device"
Manufacturer="sdr-prototypes.blogspot.com"
Product="RX888"
SerialNumber="0008012400431D31"
Device 2
FriendlyName="Cypress FX3 USB StreamerExample Device" 
Manufacturer="sdr-prototypes.blogspot.com" Product="RX888mk2" 
SerialNumber="0009023200531716"

I plan commit on Tuesday or Wednesday.
Ciao Oscar

**Comment by fventuri** [comment]
That's great news, Oscar!

At this point it might be a good idea to get in touch with Simon Brown of SDR Console to ask him if he can include the new release of the firmware with the unique S/N in the next version of his software.

Franco

**Comment by ms-jdow** [comment]
I figure once it is known working we can bug Simon. He's in a big push at the moment so I'd want things to be as easy to drop in as possible. I am also pestering him to add 128 Msps or user entered sample rate as an even better deal. (That might fix another very subtle bug he has.)

{^_^}

**Comment by ms-jdow** [comment]
I guess now it might be appropriate to see if we can reach out to the system random number generator, if I can find it, and see if we can use that if those registers are in their default setting state. I believe the key to this is "errno_t rand_s(unsigned int* randomValue);" which requires this in the file's include list:

#define _CRT_RAND_S
#include <stdlib.h>

I wonder if that can be used to generate a relatively unique ID (64 bits instead of 128) that we can use for the serial number. (I rather like the rtlsdr dongles. I can use fairly long informative strings such as "RTLSDR on Discone",)

Is that USBdescriptor.c file already a part of the project or is it from an example?

{^_^}

**Comment by fventuri** [comment]
Joanne, I am not sure what you mean when you say "if those registers are in their default setting state", since according to this post on Cypress community forums (https://community.infineon.com/t5/USB-Superspeed-Peripherals/Unique-Id-Registers-in-CYUSB3014/m-p/201273/highlight/true#M20119):

> There will be a 66bits unique ID for each die of FX3. You can read these bits from the address location 0xE0055010.

(they actually meant 64 bits, not 66)

As per the file `USBdescriptor.c`, the original (before my modifications) comes from Oscar's project, and you can find it here: https://github.com/ik1xpv/ExtIO_sddc/blob/master/SDDC_FX3/USBdescriptor.c

Franco

**Comment by ms-jdow** [comment]
Ah - so it is read only and precisely what we want for a serial number. I have not gotten the chip's addressing scheme into my head, yet. I see one of the responders to that thread was worried about the bit order and the correct way to express the unique ID. I suppose that matters if you want to complain about a specific chip to the Cypress folks. Otherwise it's just as unique either way.

{^_-}

**Comment by ik1xpv** [comment]
Joanne,
If you have time and  access to two SDRs please download and run the compiled code at [https://github.com/ik1xpv/ExtIO_sddc/actions/runs/1417405256](https://github.com/ik1xpv/ExtIO_sddc/actions/runs/1417405256)
or compile the code  at  #210 
In principle it should be able to find up to 4 FX3 devices connected to the PC and select the one to be used.
If there is a single FX3 no selection is required.
![image](https://user-images.githubusercontent.com/9883800/140098512-51fb61ae-bcc3-4715-b8bb-54340f6c7220.png)

Oscar

**Comment by ms-jdow** [comment]
This is what I got:
![image](https://user-images.githubusercontent.com/10334717/140198931-f4c292f2-3ce7-4c8c-a064-ff69713650b9.png)

The numbers are interesting. Another test coming. This is with one of them plugged into a different port.
![image](https://user-images.githubusercontent.com/10334717/140199310-dafafc3e-0157-4456-894e-2a62b37232aa.png)

It seems to work properly. Thank you! I'll pass the critical addresses along to Simon.

As a side issue - what all is involved in adding higher sample rates to the old RX666/RX888 code?

{^_^}

**Comment by ik1xpv** [comment]
Joanne,
Thanks for report.  I 'm still digging in the code to try to improve power up discovery of FX3 BootLoader devices.
Simon is informed.
The RX888 has the same sampling rate capabilities of RX888mk2,
I do not know of RX666 I imagine they cloned BBRF103 architecture. I do not know the hardware limit nor how the hardware is detected from today software.
HF103 prototype uses a fixed low noise xtal reference at 64 MHz that is not programmable.

Oscar

**Comment by ms-jdow** [comment]
I think you are saying the step from 888 to 888 MK 2 may not be a simple thing for Simon to code. (I had this insane notion of doing something like monitoring all ham bands for ALE traffic using SDR Radio and a huge number of ALE decoders. It's just to say "it can be done" even if it is silly because you almost always know what set of bands just aren't going to work and which might show some sporadic E skip.)

{^_-}
